name: Sync and publish to Github Packages

on:
  schedule:
    - cron: '1 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: dabreadman/sync-upstream-repo@v1.3.0
      with:
        upstream_repo: https://github.com/SpigotMC/BungeeCord.git
        upstream_branch: master
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: zulu
        server-id: opencollab
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAVEN_USERNAME: ${{ vars.DEPLOY_USER }}
        MAVEN_PASSWORD: ${{ secrets.DEPLOY_PASS }}
